server:
  tomcat:
    threads:
      max: 50
      min-spare: 5
    keep-alive-timeout: 15
    connection-timeout: 2s
  port: 9001
  shutdown: graceful

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: redinessState
